---
- name: launch prometheus push gateway
  become: true
  docker_container:
    name: push-gateway
    privileged: true
    detach: true
    image: "prom/pushgateway:{{ push_gateway_version }}"
    network_mode: host
    restart_policy: always
    state: started

- name: check gateway api works
  uri:
    url: http://localhost:{{ push_gateway_port }}
    method: GET
    status_code: 200
  retries: 10
  delay: 3