---
- name: Copy configs
  copy:
    src: grafana
    dest: /etc

- name: Launch grafana prometheus
  become: true
  docker_container:
    image: grafana/grafana:{{ grafana_version }}
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    name: grafana
    detach: true
    privileged: true
    network_mode: host
    restart_policy: always
    state: started
    volumes:
      - grafana_data:/var/lib/grafana
      - "{{ grafana_config_path }}/datasources:/etc/grafana/datasources"
      - "{{ grafana_config_path }}/dashboards:/etc/grafana/dashboards"
