---
- name: Install grafana python api client
  pip:
    name: "grafana_api_client"

- name: Check api status and retry until is available
  uri:
    url: "http://127.0.0.1:{{ grafana_port }}/api/admin/settings"
    method: GET
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
    status_code: 200
  register: httpresponse
  until: httpresponse.status == 200
  retries: 10
  delay: 20

- name: Copy dashboard
  copy:
    src: "dashboard.json"
    dest: "/root"
  register: dashboard

- name: Import Grafana dashboard
  grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "{{ grafana_admin_user }}"
    grafana_password: "{{ grafana_admin_password }}"
    state: present
    message: "Imported"
    overwrite: true
    path: "/root/dashboard.json"
  # Should be fixed
  ignore_errors: true
