---
- name: Create prometheus config dir
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "/etc/prometheus/targets"
    - "{{ prometheus_config_path }}"
    - "/opt/prometheus/data/"

- name: Set prometheus config
  template:
    src: configs/prometheus/prometheus.yml.j2
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    force: true
  register: prometheus_configuration

- name: create docker network
  become: true
  docker_network:
    name: "{{ prometheus_docker_network }}"
    state: present

- name: Launch docker prometheus
  become: true
  docker_container:
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      {{ prometheus_additional_command_args }}
    image: prom/prometheus:{{ prometheus_version }}
    name: prometheus
    detach: true
    network_mode: host
    recreate: "{{ prometheus_configuration.changed }}"
    restart_policy: always
    state: started
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/prometheus/targets:/etc/prometheus/targets/:ro
      - /etc/prometheus/alerts/:/etc/prometheus/alerts/:ro
      - /opt/prometheus/data/prometheus:/prometheus:rw

- name: Check prometheus API works
  uri:
    url: http://localhost:{{ prometheus_port }}
    method: GET
    status_code: [200, 405]
  retries: 15
  delay: 5
