---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu1804-promstack
    # instance_raw_config_args:
    #   - "vm.network 'forwarded_port', guest: 9090, host: 9090"
    #   - "vm.network 'forwarded_port', guest: 8080, host: 8080"
    #   - "vm.network 'forwarded_port', guest: 9100, host: 9100"
    #   - "vm.network 'forwarded_port', guest: 9091, host: 9091"
    #   - "vm.network 'forwarded_port', guest: 3000, host: 3000"
    box: ubuntu/bionic64
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlPersist=6000s -o ControlMaster=auto -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      ubuntu1804-promstack:
        ansible_python_interpreter: "/usr/bin/python"
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
