{
 "title": "CyberOS Dashboard",
 "time": { "to": "now", "from": "now-6h" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "endpoint", "label": "Server", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "AVG CPU Usage (5m)",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 4, "w": 3, "x": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 4, "w": 3, "x": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 4, "w": 3, "x": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1-(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}))*100"
    }
   ]
  },
  {
   "title": "Latest Produced Block",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 4, "w": 3, "x": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "eos_get_head_block_number" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 4, "w": 3, "x": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Graph (10s)",
   "type": "graph",
   "gridPos": { "y": 5, "h": 8, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[10s])) * 100)",
     "legendFormat": "{{ node_cpu_total }}"
    }
   ]
  },
  {
   "title": "Disks IO",
   "type": "graph",
   "gridPos": { "y": 5, "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[10s]) * 100",
     "legendFormat": "{{ SDA IO }}"
    }
   ]
  }
 ]
}